#if DEBUG
using System.Text;

namespace Campus.Desktop.Services;

/// <summary>
/// Writes a small, genuinely valid PDF.
///
/// The sample workspace needs something the PDF reader can actually open — page counts, page
/// sizes, extracted text, thumbnails, highlights. A placeholder file with a .pdf extension would
/// exercise none of that and would quietly hide every bug in the path that matters.
///
/// Hand-written rather than generated by a library because the only correct way to know the reader
/// works is to hand it bytes nothing in this codebase produced.
/// </summary>
internal static class SamplePdf
{
    public static byte[] Create(string title, IReadOnlyList<string> pages)
    {
        var output = new MemoryStream();
        var writer = new BinaryWriter(output, Encoding.ASCII, leaveOpen: true);

        var offsets = new List<long>();

        void Object(int number, string body)
        {
            offsets.Add(output.Position);
            Write($"{number} 0 obj\n{body}\nendobj\n");
        }

        void Write(string text) => writer.Write(Encoding.ASCII.GetBytes(text));

        Write("%PDF-1.4\n");
        // A binary comment marks the file as binary for tools that sniff it.
        writer.Write(new byte[] { (byte)'%', 0xE2, 0xE3, 0xCF, 0xD3, (byte)'\n' });

        // 1 catalogue, 2 page tree, 3 font, then a page and a content stream for each page.
        var pageIds = Enumerable.Range(0, pages.Count).Select(i => 4 + i * 2).ToList();

        Object(1, "<< /Type /Catalog /Pages 2 0 R >>");
        Object(2, $"<< /Type /Pages /Kids [{string.Join(" ", pageIds.Select(id => $"{id} 0 R"))}] "
                + $"/Count {pages.Count} >>");
        Object(3, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");

        for (var i = 0; i < pages.Count; i++)
        {
            var pageId = pageIds[i];
            var contentId = pageId + 1;

            Object(pageId,
                "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
                + "/Resources << /Font << /F1 3 0 R >> >> "
                + $"/Contents {contentId} 0 R >>");

            var content = Content(i == 0 ? title : $"{title} — page {i + 1}", pages[i]);
            var bytes = Encoding.ASCII.GetBytes(content);

            offsets.Add(output.Position);
            Write($"{contentId} 0 obj\n<< /Length {bytes.Length} >>\nstream\n");
            writer.Write(bytes);
            Write("\nendstream\nendobj\n");
        }

        // The cross-reference table has to name the byte offset of every object, which is why the
        // offsets were collected as they were written rather than worked out afterwards.
        var xrefPosition = output.Position;
        var count = offsets.Count + 1;

        Write($"xref\n0 {count}\n");
        Write("0000000000 65535 f \n");
        foreach (var offset in offsets) Write($"{offset:D10} 00000 n \n");

        Write($"trailer\n<< /Size {count} /Root 1 0 R >>\nstartxref\n{xrefPosition}\n%%EOF\n");

        writer.Flush();
        return output.ToArray();
    }

    private static string Content(string heading, string body)
    {
        var text = new StringBuilder();

        text.Append("BT\n/F1 22 Tf\n72 760 Td\n(").Append(Escape(heading)).Append(") Tj\nET\n");

        var y = 710;
        foreach (var line in Wrap(body, 74))
        {
            text.Append("BT\n/F1 12 Tf\n72 ").Append(y).Append(" Td\n(")
                .Append(Escape(line)).Append(") Tj\nET\n");

            y -= 20;
            if (y < 60) break;
        }

        return text.ToString();
    }

    /// <summary>Parentheses and backslashes end a PDF string early unless they are escaped.</summary>
    private static string Escape(string text) => text
        .Replace("\\", "\\\\")
        .Replace("(", "\\(")
        .Replace(")", "\\)");

    private static IEnumerable<string> Wrap(string text, int width)
    {
        var line = new StringBuilder();

        foreach (var word in text.Split(' ', StringSplitOptions.RemoveEmptyEntries))
        {
            if (line.Length + word.Length + 1 > width)
            {
                yield return line.ToString();
                line.Clear();
            }

            if (line.Length > 0) line.Append(' ');
            line.Append(word);
        }

        if (line.Length > 0) yield return line.ToString();
    }
}
#endif
