"""
Writes apps/desktop/Campus.Desktop/Design/Brand.xaml from the generated geometry.

The app must not carry a second, hand-copied version of the mark. This regenerates the resource
dictionary so the shapes drawn on screen are byte-for-byte the shapes in the exported icons.

Run:  python tools/brand/emit_xaml.py
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import logo          # noqa: E402
import wordmark      # noqa: E402

TARGET = "apps/desktop/Campus.Desktop/Design/Brand.xaml"

HEADER = """<!--
    Campus — Brand geometry

    GENERATED FILE. Produced by tools/brand/emit_xaml.py from tools/brand/logo.py and
    tools/brand/wordmark.py. Edit those, then regenerate; do not edit this file by hand, or the
    shapes on screen will drift from the exported icons.

    The mark and the wordmark carry no colour of their own — they take the foreground they are
    given, which is what lets one definition sit on a black title bar and on a white sheet.
-->
"""


def escape(value: str) -> str:
    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build() -> str:
    layers = logo.mark_layers()
    combined = logo.mark_path()
    word_paths, word_width, word_height = wordmark.wordmark()

    lines = [
        HEADER,
        '<ResourceDictionary',
        '    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
        '    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
        "",
        "    <!-- ================================================================ MARK -->",
        f'    <x:Double x:Key="Brand.Mark.Grid">{logo.GRID:g}</x:Double>',
        "",
        f'    <x:String x:Key="Brand.Mark.Path">{escape(combined)}</x:String>',
        "",
        "    <!-- The layers on their own, for the unlock animation that assembles the mark. -->",
    ]
    for index, layer in enumerate(layers, start=1):
        lines.append(f'    <x:String x:Key="Brand.Mark.Layer{index}">{escape(layer)}</x:String>')

    lines += [
        "",
        "    <!-- Nothing may enter this margin around the mark, as a fraction of its height. -->",
        '    <x:Double x:Key="Brand.Mark.ClearSpaceRatio">0.25</x:Double>',
        "",
        "    <!-- ============================================================ WORDMARK -->",
        "    <!-- Stroked, not filled: the weight below is on the same design grid as the paths. -->",
        f'    <x:Double x:Key="Brand.Wordmark.Width">{word_width:g}</x:Double>',
        f'    <x:Double x:Key="Brand.Wordmark.Height">{word_height:g}</x:Double>',
        f'    <x:Double x:Key="Brand.Wordmark.Stroke">{wordmark.STROKE:g}</x:Double>',
        f'    <x:Double x:Key="Brand.Wordmark.CapHeight">{wordmark.CAP:g}</x:Double>',
        f'    <x:Double x:Key="Brand.Wordmark.Baseline">{wordmark.BASELINE:g}</x:Double>',
        "",
    ]

    names = ["C", "A", "M", "P", "U", "S"]
    for name, path in zip(names, word_paths):
        lines.append(f'    <x:String x:Key="Brand.Wordmark.{name}">{escape(path)}</x:String>')

    lines += [
        "",
        "    <!-- All six letterforms as one path, for when the wordmark is drawn as a unit. -->",
        f'    <x:String x:Key="Brand.Wordmark.Path">{escape(" ".join(word_paths))}</x:String>',
        "",
        "    <!-- ============================================================== LOCKUP -->",
        "    <!-- Mark height and gap relative to the wordmark, in wordmark design units. -->",
        '    <x:Double x:Key="Brand.Lockup.MarkHeight">134</x:Double>',
        '    <x:Double x:Key="Brand.Lockup.Gap">34</x:Double>',
        "",
        "</ResourceDictionary>",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    content = build()
    os.makedirs(os.path.dirname(TARGET), exist_ok=True)
    with open(TARGET, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"wrote {TARGET}")
